language: node_js
node_js:
  - stable

cache:
  - yarn

install:
  - yarn install
  - npm install codecov -g

before_script:
  - yarn build

script:
  - yarn test
  - yarn lint

after_success:
  - codecov
